image: node:latest

stages:
  - test
  - build
  - deploy

variables:
  HEROKU_API_KEY: 58e574d7-1f07-49bb-8087-b0c14661fc58
  PRISMA_API_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjanFqbXJhZngzcjc4MDg2MWJhMDdqeXNiIiwiaWF0IjoxNTQ3MzA4NDI0LCJleHAiOjE1NDk5MDA0MjR9.wvGXsp5A04BgLl2UBZKwYGq-PlOHFehBtA1onNEAwy8

cache:
  paths:
    - node_modules/

testing:
  stage: test
  script:
    - echo "to be implemented"

install-dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

deploy-staging:
  stage: deploy
  script:
    - echo "deb http://toolbelt.heroku.com/ubuntu ./" > /etc/apt/sources.list.d/heroku.list
    - wget -O- https://toolbelt.heroku.com/apt/release.key | apt-key add -
    - apt-get update -qy
    - apt-get install -y heroku-toolbelt
    - apt-get install -y ruby-dev
    - gem install dpl
    - npm install -g prisma
    - prisma login --key $PRISMA_API_KEY
    - npm run prisma-deploy:staging
    - dpl --provider=heroku --app=cogito-graphql-backend --api-key=$HEROKU_API_KEY
  only:
    - development

deploy-prod:
  stage: deploy
  script:
    - echo "deb http://toolbelt.heroku.com/ubuntu ./" > /etc/apt/sources.list.d/heroku.list
    - wget -O- https://toolbelt.heroku.com/apt/release.key | apt-key add -
    - apt-get update -qy
    - apt-get install -y heroku-toolbelt
    - apt-get install -y ruby-dev
    - gem install dpl
    - npm install -g prisma
    - prisma login --key $PRISMA_API_KEY
    - npm run prisma-deploy:prod
    - dpl --provider=heroku --app=cogito-graphql-prod --api-key=$HEROKU_API_KEY
  only:
    - master
