version: '3'
services:
  server:
    build: .
    links:
      - postgres
    depends_on:
      - postgres
    ports:
      - '${SERVER_PORT}:4000'
    environment:
      POSTGRESQL_URL: ${POSTGRESQL_URL}
      APP_SECRET: ${APP_SECRET}
    networks:
      - backend-network
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    networks:
      backend-network:
        aliases:
          - postgresql.db
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
networks:
  backend-network:
