version: '3'
services:
  server:
    build: .
    links:
      - postgres
    depends_on:
      - postgres
    ports:
      - '${SERVER_PORT}:4000'
    environment:
      POSTGRESQL_URL: ${POSTGRESQL_URL}
      APP_SECRET: ${APP_SECRET}
      SIB_API_KEY: ${SIB_API_KEY}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
      GOOGLE_CLOUD_PROJECT_ID: ${GOOGLE_CLOUD_PROJECT_ID}
      GOOGLE_CLOUD_BUCKET_NAME: ${GOOGLE_CLOUD_BUCKET_NAME}
      GOOGLE_TYPE: ${GOOGLE_TYPE}
      GOOGLE_PROJECT_ID: ${GOOGLE_PROJECT_ID}
      GOOGLE_PRIVATE_KEY_ID: ${GOOGLE_PRIVATE_KEY_ID}
      GOOGLE_PRIVATE_KEY: ${GOOGLE_PRIVATE_KEY}
      GOOGLE_CLIENT_EMAIL: ${GOOGLE_CLIENT_EMAIL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_AUTH_URI: ${GOOGLE_AUTH_URI}
      GOOGLE_TOKEN_URI: ${GOOGLE_TOKEN_URI}
      GOOGLE_AUTH_PROVIDER: ${GOOGLE_AUTH_PROVIDER}
      GOOGLE_CLIENT_CERT_URL: ${GOOGLE_CLIENT_CERT_URL}
    networks:
      - backend-network
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: prisma
    networks:
      backend-network:
        aliases:
          - postgresql.db
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
networks:
  backend-network:
