version: '3'
services:
  server:
    build: .
    ports:
      - '4000:4000'
    environment:
      - PRISMA_ENDPOINT=${PRISMA_ENDPOINT}
      - PRISMA_SECRET=${PRISMA_SECRET}
      - PRISMA_MANAGEMENT_API_SECRET=${PRISMA_MANAGEMENT_API_SECRET}
      - APP_SECRET=${APP_SECRET}
      - REACT_APP_URL=${REACT_APP_URL}
      - HEROKU_APP=${HEROKU_APP}
      - SIB_API_KEY=${SIB_API_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET=${S3_BUCKET}
  prisma:
    image: prismagraphql/prisma:1.29
    restart: always
    environment:
      PRISMA_CONFIG: |
        port: 4466
          - '4466:4466'
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        databases:
          default:
            connector: postgres
            host: postgres
            user: prisma
            password: prisma
            port: 5432
            migrations: true
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
